name: Build and Push to GHCR

on:
  push:
    branches:
      - main # Dispara o build sempre que atualizar a branch main

env:
  REGISTRY: ghcr.io
  # O GitHub converte automaticamente o nome do seu repositório para minúsculo aqui
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Permissão para gravar a imagem no seu perfil

    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: actions/setup-buildx-action@v3

      - name: Autenticar no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Token automático do próprio GitHub

      - name: Extrair Tags e Labels do Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,value=${{ github.sha }}

      - name: Compilar e Enviar Imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max